import type { Metadata } from "next";
import "./globals.css";

const themeScript = `
(function () {
	try {
		var key = "next-blog-theme";
		var mode = localStorage.getItem(key) || "auto";
		var hour = new Date().getHours();
		var timedTheme = hour >= 7 && hour < 19 ? "light" : "dark";
		var theme = mode === "light" || mode === "dark" ? mode : timedTheme;
		document.documentElement.classList.toggle("dark", theme === "dark");
		document.documentElement.dataset.themeMode = mode;
		document.documentElement.style.colorScheme = theme;
	} catch (_) {}
})();
`;

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className="antialiased">
				<script dangerouslySetInnerHTML={{ __html: themeScript }} />
				{children}
			</body>
		</html>
	);
}
