import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { remark } from "remark";
import remarkGfm from "remark-gfm";

const root = process.cwd();
const postsDirectory = path.join(root, "posts");
const outputFile = path.join(root, "src", "generated", "posts.ts");

function formatTitle(slug) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function stripPositions(node) {
  delete node.position;

  if (Array.isArray(node.children)) {
    node.children.forEach(stripPositions);
  }
}

function getExcerpt(content) {
  return content
    .replace(/[#>*_`\-[\]]/g, "")
    .split("\n")
    .map((line) => line.trim())
    .find(Boolean);
}

if (!fs.existsSync(postsDirectory)) {
  fs.mkdirSync(postsDirectory, { recursive: true });
}

const posts = await Promise.all(
  fs
    .readdirSync(postsDirectory)
    .filter((fileName) => fileName.endsWith(".md"))
    .map(async (fileName) => {
      const slug = fileName.replace(/\.md$/, "");
      const source = fs.readFileSync(path.join(postsDirectory, fileName), "utf8");
      const { data, content } = matter(source);
      const parsed = remark().use(remarkGfm).parse(content);
      stripPositions(parsed);

      return {
        slug,
        title: typeof data.title === "string" ? data.title : formatTitle(slug),
        description:
          typeof data.description === "string"
            ? data.description
            : getExcerpt(content) ?? "阅读这篇 Markdown 文章。",
        date: typeof data.date === "string" ? data.date : undefined,
        content: parsed,
      };
    })
);

posts.sort((a, b) => (b.date ?? "").localeCompare(a.date ?? ""));

const generated = `// This file is generated by scripts/generate-posts.mjs. Do not edit manually.\nimport type { Root } from "mdast";\n\nexport type GeneratedPost = {\n  slug: string;\n  title: string;\n  description: string;\n  date?: string;\n  content: Root;\n};\n\nexport const generatedPosts = ${JSON.stringify(posts, null, 2)} satisfies GeneratedPost[];\n`;

fs.writeFileSync(outputFile, generated);
console.log(`Generated ${posts.length} post(s) at ${path.relative(root, outputFile)}`);
