import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { remark } from "remark";
import remarkGfm from "remark-gfm";

const root = process.cwd();
const postsDirectory = path.join(root, "posts");
const outputFile = path.join(root, "src", "generated", "posts.ts");
const pinnedTitle = "必读！关于本博客的相关信息";

function formatTitle(slug) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function stripPositions(node) {
  delete node.position;

  if (Array.isArray(node.children)) {
    node.children.forEach(stripPositions);
  }
}

function getExcerpt(content) {
  return content
    .replace(/^---[\s\S]*?---/, "")
    .replace(/[#>*_`\-[\]]/g, "")
    .split("\n")
    .map((line) => line.trim())
    .find(Boolean);
}

function getHeadingTitle(content) {
  return content
    .split("\n")
    .map((line) => line.trim())
    .find((line) => line.startsWith("# "))
    ?.replace(/^#\s+/, "")
    .trim();
}

function normalizeDate(value) {
  if (value instanceof Date && !Number.isNaN(value.getTime())) {
    return value.toISOString().slice(0, 10);
  }

  if (typeof value === "number") {
    return normalizeDate(new Date(value));
  }

  if (typeof value !== "string") {
    return undefined;
  }

  const match = value.match(/\d{4}[-/.]\d{1,2}[-/.]\d{1,2}/);
  if (!match) {
    return undefined;
  }

  return match[0]
    .replace(/[/.]/g, "-")
    .split("-")
    .map((part, index) => (index === 0 ? part.padStart(4, "0") : part.padStart(2, "0")))
    .join("-");
}

function getDate({ data, content, fileName }) {
  return (
    normalizeDate(data.date) ??
    normalizeDate(data.publishedAt) ??
    normalizeDate(data.createdAt) ??
    normalizeDate(fileName) ??
    normalizeDate(content)
  );
}

if (!fs.existsSync(postsDirectory)) {
  fs.mkdirSync(postsDirectory, { recursive: true });
}

const posts = await Promise.all(
  fs
    .readdirSync(postsDirectory)
    .filter((fileName) => fileName.endsWith(".md"))
    .map(async (fileName) => {
      const slug = fileName.replace(/\.md$/, "");
      const source = fs.readFileSync(path.join(postsDirectory, fileName), "utf8");
      const { data, content } = matter(source);
      const title = typeof data.title === "string" ? data.title : getHeadingTitle(content) ?? formatTitle(slug);
      const parsed = remark().use(remarkGfm).parse(content);
      stripPositions(parsed);

      return {
        slug,
        title,
        description:
          typeof data.description === "string"
            ? data.description
            : getExcerpt(content) ?? "阅读这篇 Markdown 文章。",
        date: getDate({ data, content, fileName }),
        pinned: data.pinned === true || title.includes(pinnedTitle),
        content: parsed,
      };
    })
);

posts.sort((a, b) => {
  if (a.pinned !== b.pinned) {
    return a.pinned ? -1 : 1;
  }

  return (b.date ?? "").localeCompare(a.date ?? "");
});

const generated = `// This file is generated by scripts/generate-posts.mjs. Do not edit manually.\nimport type { Root } from "mdast";\n\nexport type GeneratedPost = {\n  slug: string;\n  title: string;\n  description: string;\n  date?: string;\n  pinned: boolean;\n  content: Root;\n};\n\nexport const generatedPosts = ${JSON.stringify(posts, null, 2)} satisfies GeneratedPost[];\n`;

fs.writeFileSync(outputFile, generated);
console.log(`Generated ${posts.length} post(s) at ${path.relative(root, outputFile)}`);
